Update aws.yml

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -23,14 +23,29 @@ jobs:
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: us-east-1
           AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
-          EC2_KEY_PAIR_PATH: s3://finalproject1-a/Ashishkey.pem
+          EC2_KEY_PAIR_PATH: s3://requiredfiles2323/onekey.pem
           
-      - name: Start EMR cluster
+      # - name: Start EMR cluster
+      #   run: |
+      #     cluster_info=$(aws emr describe-cluster --query 'Clusters[?Name==MyEMRCluster].[Id]' --output text)
+
+      #     if [ -z "$cluster_info" ]; then
+      #         echo "Error: Cluster ID not found."
+      #     exit 1
+      #     fi
+      #     aws emr start-clusters --cluster-ids "$cluster_info"
+      #   env:
+      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      #     AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
+      #     AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
+      #     EC2_KEY_PAIR_PATH: s3://requiredfiles2323/onekey.pem
+      
+      - name: Start Crawler
         run: |
-          aws emr start-cluster --MyEMRCluster MyEMRCluster
+          aws glue start-crawler --name data-crawler
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
-          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
-          EC2_KEY_PAIR_PATH: s3://finalproject1-a/Ashishkey.pem
+          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
